name: Publish ARMDEVENV to GHCR on Commit (dev)

on:
  branches:
    - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push to GHCR
        run: |
          docker login --username dehcrep --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/dehcrep/armdevenv:dev
          docker push ghcr.io/dehcrep/armdevenv:dev
